import { RoadSectionId, StationId } from "@/common/types";
import { OffsetT } from "@/plugin/utils/offset-t";
import { RoadSection } from "../road-section";
import { Station } from "../station";
import { Node } from "../node";
import { MapState } from "../map-state";
import { RoadSectionPassData } from "@/common/messages";
import { applyLateralOffset } from "@/plugin/utils/math";
import { lineOffsetInSection } from "@/plugin/utils/constants";

export interface RoadSectionPos {
  section: RoadSection;
  offset: OffsetT;
}

export interface PassStop {
  station: Station;
  rank: number;    // lane-stacking rank at this station, same mechanism as before
  stops: boolean;  // true = real/persisted stop; false = derived pass-through (never serialized)
}

export interface SerializedRoadSectionPassStop {
  s: StationId;
  r: number;
}

export interface SerializedRoadSectionPass {
  c: RoadSectionId;
  d: 'a' | 'd';
  f: number; // fromRank
  t: number; // toRank
  s: SerializedRoadSectionPassStop[];
}

// One full traversal of exactly one RoadSection, always spanning the section's two
// real physical endpoint Nodes — a road only ever has two endpoints, so a pass never
// needs a null/dangling side the way the old RoadSectionChange did. `fromNode`/`toNode`
// are derived, not stored: storing them separately would allow an invalid state that
// doesn't match the section's actual topology.
export class RoadSectionPass {
  section!: RoadSection;
  direction!: 'ascending' | 'descending';
  fromRank!: number; // stacking rank at (section, side-of-fromNode)
  toRank!: number;   // stacking rank at (section, side-of-toNode)
  stops!: PassStop[]; // full merged (real + pass-through) list after validateLinePaths runs

  get fromNode(): Node {
    return this.direction === 'ascending' ? this.section.parentRoad.endpoints[0].node : this.section.parentRoad.endpoints[1].node;
  }

  get toNode(): Node {
    return this.direction === 'ascending' ? this.section.parentRoad.endpoints[1].node : this.section.parentRoad.endpoints[0].node;
  }

  static fromData(mapState: Readonly<MapState>, data: RoadSectionPassData): RoadSectionPass {
    const pass = new RoadSectionPass();
    pass.section = mapState.getRoadSectionHarsh(data.sectionId);
    pass.direction = data.direction;
    pass.fromRank = data.fromRank;
    pass.toRank = data.toRank;
    pass.stops = data.stops.map(s => ({
      station: mapState.getStationHarsh(s.stationId),
      rank: s.rank,
      stops: s.stops,
    }));
    return pass;
  }

  static fromSerialized(mapState: Readonly<MapState>, ser: SerializedRoadSectionPass): RoadSectionPass {
    const pass = new RoadSectionPass();
    pass.section = mapState.getRoadSectionHarsh(ser.c);
    pass.direction = ser.d === 'a' ? 'ascending' : 'descending';
    pass.fromRank = ser.f;
    pass.toRank = ser.t;
    // Only real stops are ever persisted — pass-throughs are regenerated by
    // validateLinePaths right after deserialization.
    pass.stops = ser.s.map(s => ({
      station: mapState.getStationHarsh(s.s),
      rank: s.r,
      stops: true,
    }));
    return pass;
  }

  toData(): RoadSectionPassData {
    return {
      sectionId: this.section.getRoadSectionId(),
      direction: this.direction,
      fromRank: this.fromRank,
      toRank: this.toRank,
      stops: this.stops.map(s => ({ stationId: s.station.id, rank: s.rank, stops: s.stops })),
    };
  }

  serialize(): SerializedRoadSectionPass {
    return {
      c: this.section.getRoadSectionId(),
      d: this.direction === 'ascending' ? 'a' : 'd',
      f: this.fromRank,
      t: this.toRank,
      s: this.stops.filter(s => s.stops).map(s => ({ s: s.station.id, r: s.rank })),
    };
  }

  private computeJunctionPosition(node: Node, rank: number): Vector | undefined {
    const road = this.section.parentRoad;
    const bezier = road.computeBezier();
    if (!bezier) return undefined;

    const numLines = this.section.getMaxStationStopCount();
    const totalOffset = this.section.computeOffset() + lineOffsetInSection(rank, numLines);
    const isStart = road.endpoints[0].node === node;
    const ep = road.computeEndpointPos(isStart ? 0 : 1);
    if (totalOffset === 0) return ep;
    return applyLateralOffset(ep, bezier.evalTangent(isStart ? 0 : 1), totalOffset * (isStart ? 1 : -1));
  }

  // Position of this pass's own junction marker at its fromNode/toNode end —
  // replaces RoadSectionChange.computeStartPosition/computeEndPosition.
  computeFromPosition(): Vector | undefined {
    return this.computeJunctionPosition(this.fromNode, this.fromRank);
  }

  computeToPosition(): Vector | undefined {
    return this.computeJunctionPosition(this.toNode, this.toRank);
  }

  // Replaces StationStop.computePosition — looks the stop up by station id.
  computeStopPosition(stationId: StationId): Vector | undefined {
    const stop = this.stops.find(s => s.station.id === stationId);
    if (!stop) return undefined;

    const road = this.section.parentRoad;
    const bezier = road.computeBezier();
    if (!bezier) return undefined;

    const numLines = this.section.getMaxStationStopCount();
    const effectiveCount = Math.max(numLines, stop.rank + 1);
    const totalOffset = this.section.computeOffset() + lineOffsetInSection(stop.rank, effectiveCount);
    const pos = stop.station.interpT.evalBezier(bezier);
    if (totalOffset === 0) return pos;
    return applyLateralOffset(pos, stop.station.interpT.evalBezierTangent(bezier), totalOffset);
  }

  // Section + biased offset at this pass's own start (fromNode side) / end (toNode side) —
  // same bias convention as the old RoadSectionChange/StationStop .start()/.end(), but
  // always defined since a pass never has a dangling side.
  start(): RoadSectionPos {
    const side = this.direction === 'ascending' ? 0 : 1;
    return { section: this.section, offset: new OffsetT(side, side === 0 ? 'positive' : 'negative') };
  }

  end(): RoadSectionPos {
    const side = this.direction === 'ascending' ? 1 : 0;
    return { section: this.section, offset: new OffsetT(side, side === 0 ? 'positive' : 'negative') };
  }
}
